// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDS7odP0M4XFT_B74yy03kM_ssQDnjtvVY',
    appId: '1:339173468227:android:084f2c94e27d56c8360cf6',
    messagingSenderId: '339173468227',
    projectId: 'wereat-app',
    storageBucket: 'wereat-app.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB35huxVeQ9vjTVFbiPFJS-maPMf22PvPk',
    appId: '1:339173468227:ios:cc88a1956db6a7cb360cf6',
    messagingSenderId: '339173468227',
    projectId: 'wereat-app',
    storageBucket: 'wereat-app.firebasestorage.app',
    androidClientId: '339173468227-dr31o5p0tfsomvo9567o53cjmbon5a7l.apps.googleusercontent.com',
    iosClientId: '339173468227-b50vfe5rrcoqipjvhf47b0c89oa36atq.apps.googleusercontent.com',
    iosBundleId: 'com.wereat.app',
  );
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_6ZL3bWy_72Z3XJsEONvRc0l3RaynKi4',
    appId: '1:339173468227:web:00eba9dfb8304056360cf6',
    messagingSenderId: '339173468227',
    projectId: 'wereat-app',
    authDomain: 'wereat-app.firebaseapp.com',
    storageBucket: 'wereat-app.firebasestorage.app',
  );
}
